config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    resource :attending
  end
  resources :venues 
  resources :games
 
  get "profiles/:id" => "profiles#show", as: :profile
  get "profiles" => "profiles#index"
  get "calendar" => 'profiles#calendar'

  
  root 'welcome#index'

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attending.rb
class Attending < ApplicationRecord
	belongs_to :event
	belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	# belongs_to :game
	# belongs_to :venue
	has_many :attendings

	def self.search(search)
  		Event.where("game LIKE ?", "%#{search}%")

  	
	end
	
	geocoded_by :address
  	after_validation :geocode

	validates :game, presence: true
	validates :location, presence: true
	validates :variation, presence: true
	validates :teach, presence: true
	validates :snacks, presence: true
	validates :date, presence: true
	validates :time, presence: true
	validates :players, presence: true


	
end

app/models/game.rb
class Game < ApplicationRecord
	# has_many :events

	# has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:styles/missing.png"
 #  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	validates :title, presence: true
	validates :games_type, presence: true
	validates :category, presence: true
	validates :weight, presence: true
	validates :age, presence: true
	validates :players, presence: true
	validates :table_size, presence: true
	validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
  has_many :attendings

  def attendings?(event)
    event.attendings.where(user_id: id).any?
  end

  validates :username, presence: true, uniqueness: true
end

app/models/venue.rb
class Venue < ApplicationRecord
	# has_many :events
	geocoded_by :address
  	after_validation :geocode

	validates :name, presence: true
	validates :address, presence: true
	validates :website, presence: true
	validates :venues_type, presence: true
	validates :phone, presence: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  

 protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :birthday, :location, :gender, :avatar])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :birthday, :location, :gender, :avatar])
    end

end

app/controllers/attendings_controller.rb
class AttendingsController < ApplicationController
	before_action :authenticate_user!

  def create
    @event = Event.find(params[:event_id])
    @event.attendings.where(user_id: current_user.id).first_or_create
      redirect_to request.referrer, notice: "You're attending this event!"
  end

  def destroy
    @event = Event.find(params[:event_id])
    @event.attendings.find_by(user_id: current_user.id).destroy
    redirect_to request.referrer
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :set_event, only: [:show, :edit, :update, :destroy]
	def new
      	@event = Event.new
    end

    def show
    end

    def index
    	@e = Event.all
		  if params[:search]
		    @e = Event.search(params[:search]).order("created_at DESC")
		  else
		    @e = Event.all.order('created_at DESC')
		  end
  	end

  	def edit
  	end

  	def create
	    @event = Event.new(event_params)

	    respond_to do |format|
	      if @event.save
	        format.html { redirect_to @event, notice: 'Game night was successfully created! Play on!' }
	      else
	        format.html { render :new }
	      end
	    end
  	end

  	def update
	    respond_to do |format|
	        if @event.update(event_params)
	          format.html { redirect_to @event, notice: 'Game night was successfully updated.' }
	     	else
	          format.html { render :edit }
	      	end
    	end
  	end

  	def destroy
	      @event.destroy
	    respond_to do |format|
	      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
	    end
	end

  	private

	 def event_params
	    params.require(:event).permit(:game, :user_id, :date, :time, :snacks, :variation, :teach, :location, :icon, :description, :title, :address, :players)
	 end

	 def set_event
    	@event = Event.find(params[:id])
	 end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :set_game, only: [:show, :edit, :update, :destroy]
	def new
      @game = Game.new
    end

    def show
    	@e = Event.all
    end

    def index
    	@g = Game.all
  	end

  	def edit
  	end

	def create
	    @game = Game.new(game_params)

		    respond_to do |format|
		      if @game.save
		        format.html { redirect_to @game, notice: 'Game was successfully created.' }
		      else
		        format.html { render :new }
		      end
		    end
	  	end
	

  	def update
        if @game.update(game_params)
        	redirect_to @game, notice: 'Game was successfully updated.'
     	else
        	render :edit
      	end
  	end



  	def destroy
	      @game.destroy
	    respond_to do |format|
	      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
	    end
	end
end

  	private

		def game_params
		    params.require(:game).permit(:games_type, :category, :weight, :age, :players, :table_size, :title, :description)
		end
	   	def set_game
	    	@game = Game.find(params[:id])
		end
	

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  	@event = Event.new
  end

  def calendar
  	@events = Event.all
  	@event = Event.new
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
	before_action :set_venue, only: [:show, :edit, :update, :destroy]
	def new
      @venue = Venue.new
    end

    def show
    end

    def index
    	@v = Venue.all
  	end

  	def edit
  	end

	def create
	    @venue = Venue.new(venue_params)

		    respond_to do |format|
		      if @venue.save
		        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
		      else
		        format.html { render :new }
		      end
		    end
	  	end
	

  	def update
  		respond_to do |format|
	        if @venue.update(venue_params)
	          format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
	     	else
	          format.html { render :edit }
	      	end
    	end
  	end

  	def destroy
	    @venue.destroy
	    respond_to do |format|
	      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
	    end
	end
end

  	private

		def venue_params
		    params.require(:venue).permit(:name, :address, :phone, :website, :venues_type)
		end
	   	def set_venue
	    	@venue = Venue.find(params[:id])
		end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@g = Game.all
  	@e = Event.all
  end

  def about
  end

  def contact
  end

  def games
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendings_helper.rb
module AttendingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<div class="container">
<h1>Editing Event</h1>

<%= render 'form' %>


<%= button_to 'Back', events_path, method: :get, class: 'btn btn-default' %>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>





<a  name="gamenight"></a>
<div class="container-fluid">
<br>
    <div class="port-header"><h2>Upcoming Game Nights!</h2></div>
    <br>
    <div class="row">
        
      <% event_time = "" %>
      
      <% @e.each do |event| %> 
        
        <% event_time = event.time.to_s %>
        <% event_time = event_time.reverse %>
        <% j = 0 %>
        
        <% while j < 11  do %>
          <% event_time = event_time.chop %>
          <% j += 1 %>
        <% end %>
        
        <% event_time = event_time.reverse %>

        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <% if event.icon == "Board Game" %>
              <%= image_tag('board-game-icon.png') %>
            <% elsif event.icon == "Card" %>
              <%= image_tag('card-icon.png') %>
            <% elsif event.icon == "Role Playing" %>
              <%= image_tag('rpg-icon.png') %>
            <% elsif event.icon == "Table Top" %>
              <%= image_tag('tabletop-icon.png') %>
            <% elsif event.icon == "Phoenix" %>
              <%= image_tag('phoenix.png') %>
            <% elsif event.icon == "Pirate" %>
              <%= image_tag('pirate.png') %>
            <% elsif event.icon == "Racing Flags" %>
              <%= image_tag('raceflag.png') %>
            <% elsif event.icon == "Radio Active" %>
              <%= image_tag('radioactive.png') %>
            <% elsif event.icon == "Builder" %>
              <%= image_tag('tool.png') %>
            <% elsif event.icon == "UFO" %>
              <%= image_tag('ufo.png') %>
            <% elsif event.icon == "Viking" %>
              <%= image_tag('viking.png') %>
            <% end %>
            <div class="caption">
              <h3><%= event.title %></h3>
               <p class="lead"><%= event.game %></p>
                          <p><ul>
                            <p><%= event.description[0...256] %>...
                                <%= link_to "Read More", event %>
                            </p><br>
                              <p><strong>Location:</strong> <%= event.location %></p>
                              <p><strong>When: </strong><%= event.date %> at <%= event_time %></p>
                              
                          </ul></p>
              <p><%= button_to 'More Event Info', event, method: :get, class: 'btn btn-default' %></p>
            </div>
          </div>
        </div>
      <% end %>

       
    </div>
</div>

<br>

<%= button_to 'New Event', new_event_path, method: :get, class: 'btn btn-default' %>

app/views/events/new.html.erb
<div class="container">
<h1>New Event</h1>

<%= render 'form' %>

<%= button_to 'Back', events_path, method: :get, class: 'btn btn-default' %>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>


        <div class="container">

            <div class="row">
             
              
                <center><div class="col-md-7">



                    <% if @event.icon == "Board Game" %>
                      <%= image_tag('board-game-icon.png') %>
                    <% elsif @event.icon == "Card" %>
                      <%= image_tag('card-icon.png') %>
                    <% elsif @event.icon == "Role Playing" %>
                      <%= image_tag('rpg-icon.png') %>
                    <% elsif @event.icon == "Table Top" %>
                      <%= image_tag('tabletop-icon.png') %>
                    <% elsif @event.icon == "Phoenix" %>
                      <%= image_tag('phoenix.png') %>
                    <% elsif @event.icon == "Pirate" %>
                      <%= image_tag('pirate.png') %>
                    <% elsif @event.icon == "Racing Flags" %>
                      <%= image_tag('raceflag.png') %>
                    <% elsif @event.icon == "Radio Active" %>
                      <%= image_tag('radioactive.png') %>
                    <% elsif @event.icon == "Builder" %>
                      <%= image_tag('tool.png') %>
                    <% elsif @event.icon == "UFO" %>
                      <%= image_tag('ufo.png') %>
                    <% elsif @event.icon == "Viking" %>
                      <%= image_tag('viking.png') %>
                    <% end %>
                    
                </div></center>

               

                <div class="col-md-5">

                <% event_time = @event.time.to_s %>
                <% event_time = event_time.reverse %>
                <% j = 0 %>
                
                <% while j < 11  do %>
                  <% event_time = event_time.chop %>
                  <% j += 1 %>
                <% end %>
                
                <% event_time = event_time.reverse %>

                <% num_attending = 0 %>
                <% @event.attendings.each do |attend|%>
                  <% num_attending += 1%>
                <% end %>

               
                
                    <h2 class="section-heading"><%= @event.title %></h2>
                    <p><strong>Game: </strong><%= @event.game %></p>
                    <p><strong>Location: </strong><%= @event.location %></p>
                    <p><strong>Date: </strong><%= @event.date %></p>
                    <p><strong>Time: </strong> <%= event_time %></p>
                    <p><strong>Number of Players: </strong><%= num_attending %> out of <%= @event.players %></p>

                    <p><strong>Snacks: </strong><%= @event.snacks %></p>
                    <p><strong>Variations?: </strong><%= @event.variation %></p>
                    <p><strong>Teach?: </strong><%= @event.teach %></p>
                    <br>
                    <p><strong>Description:</strong></p>
                    <p><%= @event.description %></p>


                    <% if current_user.attendings?(@event) %>
                      <%= button_to event_attending_path(@event), class: "btn btn-default", method: :delete do %>
                        Can't Play <i class="glyphicon glyphicon-remove"></i>
                        <% end %>
                    <% else %>
                      <% if num_attending >= @event.players %>
                        <p>This Gamenight is full!</p>
                      <% else %>
                        <%= button_to event_attending_path(@event), class: "btn btn-default", method: :post do %>
                        Join this game! <i class="glyphicon glyphicon-ok"></i>
                        <% end %>
                      <% end %>
                    <% end %>
                 
                     <p><strong>Players: </strong><% @event.attendings.each do |attend|%>

                          <%= attend.user.username%>
                        <% end %>
                     </p>



               
                </div>
         

        </div>
        <!-- /.container -->

</div>

<div id="event-map"></div>

<%= javascript_tag do %>
   latitude = '<%= j @event.latitude.to_s %>';
   longitude = '<%= j @event.longitude.to_s %>';
   address = '<%= j @event.address %>';
   game = '<%= j @event.game %>';
<% end %>

<%= button_to 'Back', events_path, method: :get, class: 'btn btn-default' %>

app/views/games/edit.html.erb
<div class="container">
<h1>Editing Game</h1>

<%= render 'form' %>


<%= button_to 'Back', games_path, method: :get, class: 'btn btn-default' %>
</div>

app/views/games/index.html.erb
<% link_color = "#000000" %>

<p id="notice"><%= notice %></p>

<a  name="gamenight"></a>
<div class="container-fluid">
<br>
    <div class="port-header"><h2>Games!</h2></div>
    <br>
    <div class="row">

      <% @g.each do |game| %> 
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <% if game.games_type == "Table Top" || game.games_type == "Tabletop" %>
              <%= image_tag('tabletop-icon.png') %>
              <% link_color = "#970083" %>
            <% elsif game.games_type == "Card" || game.games_type == "Card Game" %>
              <%= image_tag('card-icon.png') %>
              <% link_color =  "#188cb2" %>
            <% elsif game.games_type == "Role Playing" || game.games_type == "RPG" %>
              <%= image_tag('rpg-icon.png') %>
              <% link_color =  "#ae2121" %>
            <% elsif game.games_type == "Board Game" || game.games_type == "Boardgame"%>
              <%= image_tag('board-game-icon.png') %>
              <% link_color =  "#009760" %>
            <% end %>
            <div class="caption">
              <h3><p style="color: <%= link_color %>"><%= game.title %></p></h3>
               <p class="lead"><%= game.category %></p>
                          <p><ul>
                              <li><%= game.games_type %></li>
                              <li><%= game.weight %></li>
                              <li>Age Rating: <%= game.age %></li>
                              <li>Players: <%= game.players %></li>
                              <li><%= game.table_size %></li>
                              <li><%= game.description[0...256] %>...
                                <%= link_to "Read More", game %>
                              </li>
                          </ul></p>
              <p><%= button_to 'More Game Info', game, method: :get, class: 'btn btn-default' %></p>
            </div>
          </div>
        </div>
      <% end %>

       
    </div>
</div>



<%= button_to 'New Game', new_game_path, method: :get, class: 'btn btn-default' %>

app/views/games/new.html.erb
<div class="container">
<h1>New Game</h1>

<%= render 'form' %>

<%= button_to 'Back', games_path, method: :get, class: 'btn btn-default' %>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>


        <div class="container">

            <div class="row">
             
              
                <center><div class="col-md-7">

                      <% if @game.games_type == "Table Top" || @game.games_type == "Tabletop" %>
                        <%= image_tag('tabletop-icon.png', class: "img-responsive") %>
                        <% link_color = "#970083" %>
                      <% elsif @game.games_type == "Card" || @game.games_type == "Card Game" %>
                        <%= image_tag('card-icon.png', class: "img-responsive") %>
                        <% link_color =  "#188cb2" %>
                      <% elsif @game.games_type == "Role Playing" || @game.games_type == "RPG" %>
                        <%= image_tag('rpg-icon.png', class: "img-responsive") %>
                        <% link_color =  "#ae2121" %>
                      <% elsif @game.games_type == "Board Game" || @game.games_type == "Boardgame"%>
                        <%= image_tag('board-game-icon.png', class: "img-responsive") %>
                        <% link_color =  "#009760" %>
                      <% end %>
                    
                </div></center>

               

                <div class="col-md-5">

               
                
                    <h2 class="section-heading"><%= @game.title %></h2>
                    <p><strong>Type: </strong><%= @game.games_type %></p>
                    <p><strong>Category: </strong><%= @game.category %></p>
                    <p><strong>Age: </strong><%= @game.age %></p>
                    <p><strong>Weight: </strong><%= @game.weight %></p>
                    <p><strong># Players: </strong><%= @game.players %></p>
                    <br>
                    <p><strong>Description:</strong></p>
                    <p><%= @game.description %></p>

                   
                    <%= button_to 'Host This Game', new_event_path, method: :get, class: 'btn btn-default' %>
                   

               <br>
                </div>
                <br>
                <br>
                </div>
                </div>
                
                <div class="container-fluid">
                <br>

                <center><h2>Upcoming game nights for <%= @game.title %></h2></center>

                <br>
                
            
                 <% @e.each do |event| %> 
                    <% if event.game == @game.title %>
                        <% event_time = event.time.to_s %>
                        <% event_time = event_time.reverse %>
                        <% j = 0 %>
                        
                        <% while j < 11  do %>
                          <% event_time = event_time.chop %>
                          <% j += 1 %>
                        <% end %>
                        
                        <% event_time = event_time.reverse %>

                        <div class="col-sm-6 col-md-4">
                          <div class="thumbnail">
                            <% if event.icon == "Board Game" %>
                              <%= image_tag('board-game-icon.png') %>
                            <% elsif event.icon == "Card" %>
                              <%= image_tag('card-icon.png') %>
                            <% elsif event.icon == "Role Playing" %>
                              <%= image_tag('rpg-icon.png') %>
                            <% elsif event.icon == "Table Top" %>
                              <%= image_tag('tabletop-icon.png') %>
                            <% elsif event.icon == "Phoenix" %>
                              <%= image_tag('phoenix.png') %>
                            <% elsif event.icon == "Pirate" %>
                              <%= image_tag('pirate.png') %>
                            <% elsif event.icon == "Racing Flags" %>
                              <%= image_tag('raceflag.png') %>
                            <% elsif event.icon == "Radio Active" %>
                              <%= image_tag('radioactive.png') %>
                            <% elsif event.icon == "Builder" %>
                              <%= image_tag('tool.png') %>
                            <% elsif event.icon == "UFO" %>
                              <%= image_tag('ufo.png') %>
                            <% elsif event.icon == "Viking" %>
                              <%= image_tag('viking.png') %>
                            <% end %>
                            <div class="caption">
                              <h3><%= event.title %></h3>
                               <p class="lead"><%= event.game %></p>
                                          <p><ul>
                                            <p><%= event.description[0...256] %>...
                                                <%= link_to "Read More", event %>
                                            </p><br>
                                              <p><strong>Location:</strong> <%= event.location %></p>
                                              <p><strong>When: </strong><%= event.date %> at <%= event_time %></p>
                                              
                                          </ul></p>
                              <p><%= button_to 'More Event Info', event, method: :get, class: 'btn btn-default' %></p>
                            </div>
                          </div>
                        </div>
                    <% else %>
                  <% end%>
                    
                <% end %>
        
          </div>
        
        <!-- /.container -->

</div>



<%= button_to 'Back', games_path, method: :get, class: 'btn btn-default' %>
     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamenight</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="google-site-verification" content="L59h4kIkV15VGYsO6sc0Ar0uN2tq430aEPxbeVNoVrs" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
   <%= stylesheet_link_tag    'application', media: 'all' %>
   <%= javascript_include_tag 'application' %>
   <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
   <%= javascript_include_tag"https://maps.googleapis.com/maps/api/js?key=AIzaSyAdDFbE6N5x90KgbFfBFf2xbrV_7cmWEJU" %>
   <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
<%= csrf_meta_tags %>

  </head>

  <% if user_signed_in? %>
    <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("navlogo.png", :class => "style_image"), root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       
        <div class="navbar-form navbar-left"> <!-- changed to div from form, form used for searches -->

        <%= form_tag(events_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], style: "width: 250px;", placeholder: "Type a game and let's play!" %>
       <%= submit_tag "Search", class: "btn btn-default" %>
       <% end %>

         

        </div>
        <ul class="nav navbar-nav navbar-right">
         <ul class="nav navbar-nav">
         
          <li><%= link_to "Find a Game Night", events_path, class: "navbar-brand" %></li>
          <li><%= link_to "Browse by Venue", venues_path, class: "navbar-brand" %></li>
          <li><%= link_to "Browse by Game", games_path, class: "navbar-brand" %></li>
       
        </ul>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile", profile_path(current_user) %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><% if user_signed_in? %>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
              <% end %></li>
            </ul>
          </li>
        </ul>
      </div> <!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% else %>
    <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= image_tag("navlogo.png", class: "style_image1") %><i class="navbar-header"></i>
      </div>

    </div><!-- /.container-fluid -->
  </nav>
<% end %>
  <body>   
    <%= yield %>
  </body>



 <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a><%= link_to "Home", root_path %></a>
                        </li>
                         <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a><%= link_to "About GameNights", about_path %></a>
                        </li>
                        
                    </ul>

                       <hr>


                    <div class="rights">
                      <p class="copyright text-muted small">&copy; 2016 <strong>GameNight & Doug Watson  </strong>All Rights Reserved</p>
                      <p class="copyright text-muted small">Photo Credit: <a href="https://www.flickr.com/photos/46259794@N02/27824441794/">derekbruff</a> Flickr via <a href="http://compfight.com">Compfight</a> <a href="https://creativecommons.org/licenses/by-nc/2.0/">cc</a></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
<br>

<br>

</html>

app/views/welcome/index.html.erb
<div class="hero-unit">
  <div>
    <br><br><br><br><br>
    <center><h1>Find Friends to Play Your Favorite Games</h1></center>
    <center><h2>and find the perfect place to play</h2></center>
    <br>
    <center><%= button_to "Find the perfect game night", events_path, method: :get, class: "btn btn-default" %><center>
    <br>
      <center><%= link_to "or browse by game.", games_path %></p></center>
  </div>
</div>

<div class="container-fluid">
<br>
<h1><center>Upcoming Events</center></h1>
<br>
<br>
<br>


<div class="row"> 
  <% @e.each do |event| %> 
        
        <% event_time = event.time.to_s %>
        <% event_time = event_time.reverse %>
        <% j = 0 %>
        
        <% while j < 11  do %>
          <% event_time = event_time.chop %>
          <% j += 1 %>
        <% end %>
        
        <% event_time = event_time.reverse %>

        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <% if event.icon == "Board Game" %>
              <%= image_tag('board-game-icon.png') %>
            <% elsif event.icon == "Card" %>
              <%= image_tag('card-icon.png') %>
            <% elsif event.icon == "Role Playing" %>
              <%= image_tag('rpg-icon.png') %>
            <% elsif event.icon == "Table Top" %>
              <%= image_tag('tabletop-icon.png') %>
            <% elsif event.icon == "Phoenix" %>
              <%= image_tag('phoenix.png') %>
            <% elsif event.icon == "Pirate" %>
              <%= image_tag('pirate.png') %>
            <% elsif event.icon == "Racing Flags" %>
              <%= image_tag('raceflag.png') %>
            <% elsif event.icon == "Radio Active" %>
              <%= image_tag('radioactive.png') %>
            <% elsif event.icon == "Builder" %>
              <%= image_tag('tool.png') %>
            <% elsif event.icon == "UFO" %>
              <%= image_tag('ufo.png') %>
            <% elsif event.icon == "Viking" %>
              <%= image_tag('viking.png') %>
            <% end %>
            <div class="caption">
              <h3><%= event.title %></h3>
               <p class="lead"><%= event.game %></p>
                          <p><ul>
                            <p><%= event.description[0...256] %>...
                                <%= link_to "Read More", event %>
                            </p><br>
                              <p><strong>Location:</strong> <%= event.location %></p>
                              <p><strong>When: </strong><%= event.date %> at <%= event_time %></p>
                              
                          </ul></p>
              <p><%= button_to 'More Event Info', event, method: :get, class: 'btn btn-default' %></p>
            </div>
          </div>
        </div>
      <% end %>
</div>
</div>